# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
project_name: spikeball-league

builds:
  - env:
      - CGO_ENABLED=0
    id: spikeball-league
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.BuildVersion=v{{.Version}}
      - -s -w -X main.BuildCommit={{.Commit}}

archives:
  - id: homebrew-tar
    formats: [tar.gz]
    name_template: "{{.ProjectName}}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  - id: binary-release
    formats: [binary]
    name_template: "{{.ProjectName}}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mode: 0755

dockers_v2:
  - images:
      - ghcr.io/marcel2603/spikeball-league/spikeball-league
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    tags:
      - latest
      - "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: keep-existing

homebrew_casks:
  - ids:
      - homebrew-tar

    repository:
      owner: Marcel2603
      name: homebrew-tap

    directory: Casks

    homepage: "https://marcel2603.github.io/spikeball-league"
    description: "Tiny Terraform coach"
    license: "Apache-2.0"

    binaries:
      - spikeball-league
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spikeball-league"]
          end
