// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(theme string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row justify-content-center\"><div class=\"col-md-8 col-lg-6 text-center\"><h1 class=\"header-title mb-3\">Spikeball Leagues</h1><p class=\"text-muted mb-5\">Create a league, share the link, and track your matches.</p><div class=\"card shadow-sm mb-5 border-0\"><div class=\"card-body p-4\"><form hx-post=\"/leagues\" class=\"d-flex gap-2\"><input type=\"text\" name=\"name\" placeholder=\"Enter League Name\" required class=\"form-control form-control-lg\"> <button type=\"submit\" class=\"btn btn-primary btn-lg px-4\">Create</button></form></div></div><div x-data=\"{ leagues: [] }\" x-init=\"\n\t\t\t\t\tlet saved = JSON.parse(localStorage.getItem('my_leagues') || '[]');\n\t\t\t\t\t(async () => {\n\t\t\t\t\t\tlet valid = [];\n\t\t\t\t\t\tfor (let i = 0; i < saved.length; i++) {\n\t\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\t\tlet res = await fetch('/leagues/' + saved[i].id + '/exists');\n\t\t\t\t\t\t\t\tif (res.ok) {\n\t\t\t\t\t\t\t\t\tvalid.push(saved[i]);\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t} catch (e) {\n\t\t\t\t\t\t\t\tvalid.push(saved[i]); // keep it if network fails\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t\tlocalStorage.setItem('my_leagues', JSON.stringify(valid));\n\t\t\t\t\t\tleagues = valid;\n\t\t\t\t\t})();\n\t\t\t\t\" x-cloak><template x-if=\"leagues.length > 0\"><div class=\"text-start\"><h4 class=\"header-title mb-3\">Your Leagues</h4><div class=\"list-group shadow-sm\"><template x-for=\"league in leagues\" :key=\"league.id\"><a x-bind:href=\"league.isAdmin ? '/admin/' + league.id : '/league/' + league.id\" class=\"list-group-item list-group-item-action d-flex justify-content-between align-items-center py-3\"><div><span x-text=\"league.name\" class=\"fw-medium\"></span></div><span x-show=\"league.isAdmin\" class=\"badge bg-primary rounded-pill\">Admin</span></a></template></div></div></template></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Home", theme).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
