// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"description\" content=\"Spikeball-League\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Spikeball League</title><!-- link rel=\"icon\" href=\"./../static/favicon.png\" type=\"image/png\"/--><!-- Google Fonts: Outfit --><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\"><link href=\"./../static/bootstrap.min.css\" rel=\"stylesheet\"><script defer src=\"./../static/alpine.min.js\"></script><script defer src=\"./../static/htmx.min.js\"></script><script defer src=\"./../static/htmx-response-target.js\"></script><script src=\"./../static/bootstrap.bundle.min.js\"></script><style>\r\n\t\t\t</style></head><body><main class=\"max-w-2xl mx-auto mt-20 text-center\"><h1 class=\"text-4xl font-bold mb-4\">Spikeball Leagues</h1><p class=\"text-gray-600 mb-8\">Generate a league. Share the link. Track stats.</p><form hx-post=\"/leagues\" class=\"flex gap-4 justify-center mb-16\"><input type=\"text\" name=\"league_name\" placeholder=\"League Name...\" required class=\"border rounded px-4 py-2 w-64\"> <button type=\"submit\" style=\"background-color: #0a53be\" class=\"text-dark px-6 py-2 rounded font-semibold hover:bg-orange-700\">Create</button></form></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
