// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type League struct {
	ID        int64     `json:"id"`
	PublicID  string    `json:"public_id"`
	AdminID   string    `json:"admin_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Match struct {
	ID         int64     `json:"id"`
	LeagueID   int64     `json:"league_id"`
	Team1ID    int64     `json:"team1_id"`
	Team2ID    int64     `json:"team2_id"`
	Team1Score int64     `json:"team1_score"`
	Team2Score int64     `json:"team2_score"`
	CreatedAt  time.Time `json:"created_at"`
}

type Player struct {
	ID        int64     `json:"id"`
	LeagueID  int64     `json:"league_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Team struct {
	ID        int64     `json:"id"`
	LeagueID  int64     `json:"league_id"`
	Name      string    `json:"name"`
	Player1ID int64     `json:"player1_id"`
	Player2ID int64     `json:"player2_id"`
	CreatedAt time.Time `json:"created_at"`
}
