// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const addPlayer = `-- name: AddPlayer :one
INSERT INTO players (league_id, name)
VALUES (?, ?)
RETURNING id, league_id, name, created_at
`

type AddPlayerParams struct {
	LeagueID int64  `json:"league_id"`
	Name     string `json:"name"`
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, addPlayer, arg.LeagueID, arg.Name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const addTeam = `-- name: AddTeam :one
INSERT INTO teams (league_id, name, player1_id, player2_id)
VALUES (?, ?, ?, ?)
RETURNING id, league_id, name, player1_id, player2_id, created_at
`

type AddTeamParams struct {
	LeagueID  int64  `json:"league_id"`
	Name      string `json:"name"`
	Player1ID int64  `json:"player1_id"`
	Player2ID int64  `json:"player2_id"`
}

func (q *Queries) AddTeam(ctx context.Context, arg AddTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, addTeam,
		arg.LeagueID,
		arg.Name,
		arg.Player1ID,
		arg.Player2ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Name,
		&i.Player1ID,
		&i.Player2ID,
		&i.CreatedAt,
	)
	return i, err
}

const checkLeagueExists = `-- name: CheckLeagueExists :one
SELECT 1 FROM leagues
WHERE admin_id = ? OR public_id = ?
LIMIT 1
`

type CheckLeagueExistsParams struct {
	AdminID  string `json:"admin_id"`
	PublicID string `json:"public_id"`
}

func (q *Queries) CheckLeagueExists(ctx context.Context, arg CheckLeagueExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkLeagueExists, arg.AdminID, arg.PublicID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLeague = `-- name: CreateLeague :one
INSERT INTO leagues (public_id, admin_id, name)
VALUES (?, ?, ?)
RETURNING id, public_id, admin_id, name, created_at
`

type CreateLeagueParams struct {
	PublicID string `json:"public_id"`
	AdminID  string `json:"admin_id"`
	Name     string `json:"name"`
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRowContext(ctx, createLeague, arg.PublicID, arg.AdminID, arg.Name)
	var i League
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AdminID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLeague = `-- name: DeleteLeague :exec
DELETE FROM leagues
WHERE admin_id = ?
`

func (q *Queries) DeleteLeague(ctx context.Context, adminID string) error {
	_, err := q.db.ExecContext(ctx, deleteLeague, adminID)
	return err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches
WHERE id = ? AND league_id = ?
`

type DeleteMatchParams struct {
	ID       int64 `json:"id"`
	LeagueID int64 `json:"league_id"`
}

func (q *Queries) DeleteMatch(ctx context.Context, arg DeleteMatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteMatch, arg.ID, arg.LeagueID)
	return err
}

const getLeagueByAdminID = `-- name: GetLeagueByAdminID :one
SELECT id, public_id, admin_id, name, created_at FROM leagues
WHERE admin_id = ? LIMIT 1
`

func (q *Queries) GetLeagueByAdminID(ctx context.Context, adminID string) (League, error) {
	row := q.db.QueryRowContext(ctx, getLeagueByAdminID, adminID)
	var i League
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AdminID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getLeagueByPublicID = `-- name: GetLeagueByPublicID :one
SELECT id, public_id, admin_id, name, created_at FROM leagues
WHERE public_id = ?
`

func (q *Queries) GetLeagueByPublicID(ctx context.Context, publicID string) (League, error) {
	row := q.db.QueryRowContext(ctx, getLeagueByPublicID, publicID)
	var i League
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.AdminID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchesByLeagueID = `-- name: GetMatchesByLeagueID :many
SELECT id, league_id, team1_id, team2_id, team1_score, team2_score, created_at FROM matches
WHERE league_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetMatchesByLeagueID(ctx context.Context, leagueID int64) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getMatchesByLeagueID, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Team1ID,
			&i.Team2ID,
			&i.Team1Score,
			&i.Team2Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByLeagueID = `-- name: GetPlayersByLeagueID :many
SELECT id, league_id, name, created_at FROM players
WHERE league_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetPlayersByLeagueID(ctx context.Context, leagueID int64) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersByLeagueID, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsByLeagueID = `-- name: GetTeamsByLeagueID :many
SELECT id, league_id, name, player1_id, player2_id, created_at FROM teams
WHERE league_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetTeamsByLeagueID(ctx context.Context, leagueID int64) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getTeamsByLeagueID, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Name,
			&i.Player1ID,
			&i.Player2ID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logMatch = `-- name: LogMatch :one
INSERT INTO matches (
    league_id, team1_id, team2_id, team1_score, team2_score
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, league_id, team1_id, team2_id, team1_score, team2_score, created_at
`

type LogMatchParams struct {
	LeagueID   int64 `json:"league_id"`
	Team1ID    int64 `json:"team1_id"`
	Team2ID    int64 `json:"team2_id"`
	Team1Score int64 `json:"team1_score"`
	Team2Score int64 `json:"team2_score"`
}

func (q *Queries) LogMatch(ctx context.Context, arg LogMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, logMatch,
		arg.LeagueID,
		arg.Team1ID,
		arg.Team2ID,
		arg.Team1Score,
		arg.Team2Score,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Team1ID,
		&i.Team2ID,
		&i.Team1Score,
		&i.Team2Score,
		&i.CreatedAt,
	)
	return i, err
}

const removePlayer = `-- name: RemovePlayer :exec
DELETE FROM players
WHERE id = ? AND league_id = ?
`

type RemovePlayerParams struct {
	ID       int64 `json:"id"`
	LeagueID int64 `json:"league_id"`
}

func (q *Queries) RemovePlayer(ctx context.Context, arg RemovePlayerParams) error {
	_, err := q.db.ExecContext(ctx, removePlayer, arg.ID, arg.LeagueID)
	return err
}

const removeTeam = `-- name: RemoveTeam :exec
DELETE FROM teams
WHERE id = ? AND league_id = ?
`

type RemoveTeamParams struct {
	ID       int64 `json:"id"`
	LeagueID int64 `json:"league_id"`
}

func (q *Queries) RemoveTeam(ctx context.Context, arg RemoveTeamParams) error {
	_, err := q.db.ExecContext(ctx, removeTeam, arg.ID, arg.LeagueID)
	return err
}
