// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddPlayer(ctx context.Context, arg AddPlayerParams) (Player, error)
	AddTeam(ctx context.Context, arg AddTeamParams) (Team, error)
	CheckLeagueExists(ctx context.Context, arg CheckLeagueExistsParams) (int64, error)
	CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error)
	DeleteLeague(ctx context.Context, adminID string) error
	DeleteMatch(ctx context.Context, arg DeleteMatchParams) error
	GetLeagueByAdminID(ctx context.Context, adminID string) (League, error)
	GetLeagueByPublicID(ctx context.Context, publicID string) (League, error)
	GetMatchesByLeagueID(ctx context.Context, leagueID int64) ([]Match, error)
	GetPlayersByLeagueID(ctx context.Context, leagueID int64) ([]Player, error)
	GetTeamsByLeagueID(ctx context.Context, leagueID int64) ([]Team, error)
	LogMatch(ctx context.Context, arg LogMatchParams) (Match, error)
	RemovePlayer(ctx context.Context, arg RemovePlayerParams) error
	RemoveTeam(ctx context.Context, arg RemoveTeamParams) error
}

var _ Querier = (*Queries)(nil)
